version: '3.8'
services:
  postgres-test:
    container_name: postgres-test
    image: postgres:15
    restart: on-failure
    volumes:
     - ./compose-data/postgres-test:/var/lib/pgsql/data
    ports:
     - 5433:5432
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - PGDATA=${PGDATA}
     - POSTGRES_DB=${POSTGRES_DB}
    networks:
     - postgresql-net
    healthcheck:
     test: [ "CMD-SHELL", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - postgresql-net

networks:
  postgresql-net:
    driver: bridge
