spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 минут (в мс)
      cache-null-values: false

  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:testTask}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:testTask}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  properties:
    hibernate:
    format_sql: true
app:
  security:
    refreshTokenDurationMs: 600000000
    jwtSecret: "======================TestTaskApp==========================="
    jwtExpirationMs: 1800000
    jwtCookie: "test-jwt"
    jwtRefreshCookie: "test-jwt-refresh"
